name: NoblePets
version: '${version}'
main: com.github.cybellereaper.noblepets.NoblePetsPlugin
api-version: '1.21'
commands:
  noblepet:
    description: Manage your magical companion.
    usage: /<command> <help|summon|dismiss|stats|talents|mount|dismount|fly|land|breed|debug>
permissions:
  noblepets.command.*:
    description: Access to all NoblePets commands.
    default: true
    children:
      noblepets.command.help: true
      noblepets.command.summon: true
      noblepets.command.dismiss: true
      noblepets.command.stats: true
      noblepets.command.talents: true
      noblepets.command.mount: true
      noblepets.command.dismount: true
      noblepets.command.fly: true
      noblepets.command.land: true
      noblepets.command.breed: true
      noblepets.command.debug: false
  noblepets.command.help:
    description: View NoblePets help information.
    default: true
  noblepets.command.summon:
    description: Summon or respawn your pet.
    default: true
  noblepets.command.dismiss:
    description: Dismiss your pet.
    default: true
  noblepets.command.stats:
    description: View pet statistics.
    default: true
  noblepets.command.talents:
    description: View pet talents.
    default: true
  noblepets.command.mount:
    description: Ride your pet.
    default: true
  noblepets.command.dismount:
    description: Stop riding your pet.
    default: true
  noblepets.command.fly:
    description: Enable flight with your pet.
    default: true
  noblepets.command.land:
    description: Land and disable pet flight.
    default: true
  noblepets.command.breed:
    description: Breed your pet with another player's.
    default: op
  noblepets.command.debug:
    description: View raw NoblePets debug data.
    default: op
